# Generated by Django 4.1.3 on 2022-11-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.TextField()),
                ('device', models.TextField()),
                ('product_id', models.PositiveIntegerField()),
            ],
        ),
    ]
