# Generated by Django 4.1.3 on 2022-11-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
    ]
