# Generated by Django 4.1.3 on 2022-11-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_order_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
