# Generated by Django 4.1.3 on 2022-11-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='products/')),
                ('image2', models.FileField(upload_to='products/')),
                ('content', models.TextField()),
                ('device', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
