# Generated by Django 4.1.3 on 2022-11-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='device',
        ),
        migrations.AlterField(
            model_name='product',
            name='device',
            field=models.CharField(choices=[('iPhone XR', 'iPhone XR'), ('iPhone 11', 'iPhone 11'), ('iPhone 12', 'iPhone 12'), ('iPhone 12 Pro', 'iPhone 12 Pro'), ('iPhone 12 Pro Max', 'iPhone 12 Pro Max'), ('iPhone 13', 'iPhone 13'), ('iPhone 13 Pro', 'iPhone 13 Pro'), ('iPhone 13 Pro Max', 'iPhone 13 Pro Max')], default='iPhone 11', max_length=20),
        ),
    ]
